### PR TITLE
make some small bug fixes and add proper category and group for Resou…

### PR DESCRIPTION
**Pull request by ajreckof**
I wanted to use to use what you have done to make a custom inspector for myself and i made some bug fixes and some upgrade to it so I thought i would share them with you since you helped me a lot. 

bug found and corrected : 
- index instead of id in type switcher which would then create wrong types (RID when clicking Object, Object when clicking Dictionary etc.., and the last PackedArray couldn't be instanciated at all)
- in some malicious case you could get `Object[path]` to return an error as `path` couldn't be accessed from `Object` so replaced it with `Object.get(path)` as it can't raise an error

upgrades : 
- Added category and group in Object editor (needed a some rework of functions and Controls
- Added a quick Delete button
- Made way for all types by replacing TYPE_OBJECT with the name of the class. This could be used for Typed Array (didi it as it was needed for my personal project)
- upgraded a bunch of code to go with 4.0 standard instead of 3.0 legacy usage

### CODE REVIEW

**Comment by don-tnowe** [comment]
🤔 I take issue with people submitting 342 file changes consisting mostly of style changes in **the same commit with some actual useful changes** (*like, yeah this is easier to understand but also gives me anxiety lol*)

Still, thank you for the work! I'll sort it out and merge some improvements.

**Comment by don-tnowe** [comment]
Some things are broken, I'll make my own push with only some changes from here, but including fixes. Thank you!

**Comment by ajreckof** [comment]
Yeah realised I forgot to push the last part 😅 sorry

**Comment by ajreckof** [comment]
Hope it will still help

**Pull request closed without merging**
